-- CREATE DATABASE DB_CRM_SA;
-- USE DB_CRM_SA;
CREATE TABLE USUARIO (
	UUID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(255) NOT NULL UNIQUE,
    PASS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)
);
INSERT INTO USUARIO (USUARIO, PASS, EMAIL) 
	VALUES ('admin', 'admin', 'admin@admin.com');

CREATE TABLE PROYECTO (
    UUID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL
);
CREATE TABLE EMPLEADO (
    UUID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL
);
CREATE TABLE UNIDAD (
    UUID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(20) NOT NULL
);
CREATE TABLE TAREA (
    UUID INT AUTO_INCREMENT PRIMARY KEY,
    UUID_PROYECTO INT NOT NULL,
    UUID_EMPLEADO INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
    CANTIDAD DECIMAL(10, 2) NOT NULL,
    UUID_UNIDAD INT NOT NULL,
    DESCUENTO DECIMAL(10, 2),
    LIQUIDO_RECIBIR DECIMAL(10, 2),
    TOTAL DECIMAL(10, 2),
    ISR DECIMAL(10, 2),
    IVA DECIMAL(10, 2),
    TOTAL_IVA DECIMAL(10, 2),
    ESTADO VARCHAR(50) NOT NULL,
    FECHA DATE NOT NULL,
    FOREIGN KEY (UUID_PROYECTO) REFERENCES PROYECTO (UUID),
    FOREIGN KEY (UUID_EMPLEADO) REFERENCES EMPLEADO (UUID),
    FOREIGN KEY (UUID_UNIDAD) REFERENCES UNIDAD (UUID)
);
CREATE OR REPLACE VIEW vw_data_instaladores AS
    SELECT 
		t.UUID AS ID,
        e.NOMBRE AS EMPLEADO,
        p.NOMBRE AS PROYECTO,
        t.DESCRIPCION AS DESCRIPCION,
        t.PRECIO_UNITARIO AS PRECIO_UNITARIO,
        t.CANTIDAD AS CANTIDAD,
        u.TIPO AS UNIDAD,
        t.DESCUENTO AS DESCUENTO,
        t.LIQUIDO_RECIBIR AS LIQUIDO_RECIBIR,
        t.ISR AS ISR,
        t.IVA AS IVA,
        t.TOTAL AS TOTAL,
        t.TOTAL_IVA AS TOTAL_IVA,
        t.ESTADO AS ESTADO,
        t.FECHA AS FECHA
    FROM tarea t JOIN empleado e ON t.UUID_EMPLEADO = e.UUID
        JOIN proyecto p ON t.UUID_PROYECTO = p.UUID
        JOIN unidad u ON t.UUID_UNIDAD = u.UUID
	WHERE t.ESTADO != 'ELIMINADO'
    ORDER BY P.NOMBRE, t.PRECIO_UNITARIO;
CREATE OR REPLACE VIEW VW_Tarea AS
SELECT 
	t.UUID AS ID,
	e.NOMBRE AS EMPLEADO,
	p.NOMBRE AS PROYECTO,
	t.DESCRIPCION AS DESCRIPCION,
	t.PRECIO_UNITARIO AS PRECIO_UNITARIO,
	t.CANTIDAD AS CANTIDAD,
	u.tipo AS UNIDAD,
	t.ESTADO AS ESTADO,
	t.FECHA AS FECHA,
    t.DESCUENTO AS DESCUENTO
FROM tarea t JOIN empleado e ON t.UUID_EMPLEADO = e.UUID
	JOIN proyecto p ON t.UUID_PROYECTO = p.UUID
	JOIN unidad u ON t.UUID_UNIDAD = u.UUID;
COMMIT;

-- INSERT's 
INSERT INTO Unidad (tipo) 
VALUES ('Jornal'),('m2'),('global'),('ml'),('noche'),('Hr. Extra');

-- DELETE's 
-- DROP TABLE TAREA;
-- DROP TABLE PROYECTO;
-- DROP TABLE UNIDAD;
-- DROP TABLE USUARIO;
-- DROP TABLE EMPLEADO;

